src/Core/Entity/User.php
<?php

declare(strict_types=1);

namespace Forumify\Core\Entity;

use ApiPlatform\Metadata\ApiResource;
use DateTime;
use Deprecated;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Forumify\Api\Serializer\Attribute\Asset;
use Forumify\Core\Repository\UserRepository;
use Forumify\Forum\Entity\Badge;
use Forumify\Forum\Entity\Subscription;
use Forumify\OAuth\Entity\OAuthClient;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Serializer\Attribute\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ApiResource(operations: [])]
class User implements AuthorizableInterface, PasswordAuthenticatedUserInterface, AuditableEntityInterface
{
    use IdentifiableEntityTrait;
    use BlameableEntityTrait;
    use TimestampableEntityTrait;

    /** @var non-empty-string $username*/
    #[ORM\Column(length: 32, unique: true)]
    #[Groups(['MessageThread'])]
    private string $username;

    #[ORM\Column(length: 128, unique: true, nullable: true)]
    private ?string $email = null;

    /** @var Collection<int, Role> */
    #[ORM\ManyToMany(targetEntity: Role::class, inversedBy: 'users', cascade: ['persist'], fetch: 'EXTRA_LAZY')]
    #[ORM\JoinTable(
        'user_role',
        joinColumns: [new ORM\JoinColumn('user', onDelete: 'CASCADE')],
        inverseJoinColumns: [new ORM\JoinColumn('role', onDelete: 'CASCADE')],
    )]
    #[ORM\OrderBy(['position' => 'ASC'])]
    private Collection $roles;

    #[ORM\Column(length: 255, nullable: true)]
    #[SensitiveField]
    private ?string $password = null;

    #[ORM\Column(length: 32)]
    #[Groups(['MessageThread'])]
    private string $displayName = '';

    /**
     * ISO 639-1 representation of the user's language
     */
    #[ORM\Column(length: 2, options: ['fixed' => true])]
    private string $language = 'en';

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $timezone = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['MessageThread'])]
    #[Asset('forumify.avatar')]
    private ?string $avatar = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $signature = null;

    #[ORM\Column(type: 'boolean')]
    private bool $emailVerified = false;

    #[ORM\Column(type: 'boolean')]
    private bool $banned = false;

    #[ORM\Column(type: 'datetime', nullable: true)]
    #[AuditExcludedField]
    private ?DateTime $lastActivity = null;

    /** @var Collection<int, Subscription> */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Subscription::class, fetch: 'EXTRA_LAZY')]
    private Collection $subscriptions;

    /** @var Collection<int, UserNotificationSettings> */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserNotificationSettings::class, cascade: ['persist'], fetch: 'EXTRA_LAZY')]
    private Collection $notificationSettings;

    /**
     * @var Collection<int, Badge>
     */
    #[ORM\ManyToMany(targetEntity: Badge::class, inversedBy: 'users', cascade: ['persist'], fetch: 'EXTRA_LAZY')]
    #[ORM\JoinTable(
        'user_badge',
        joinColumns: [new ORM\JoinColumn('user', onDelete: 'CASCADE')],
        inverseJoinColumns: [new ORM\JoinColumn('badge', onDelete: 'CASCADE')],
    )]
    #[ORM\OrderBy(['position' => 'ASC'])]
    private Collection $badges;

    #[ORM\OneToOne(targetEntity: OAuthClient::class, inversedBy: 'user')]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?OAuthClient $oAuthClient = null;

    public function __construct()
    {
        $this->roles = new ArrayCollection();
        $this->notificationSettings = new ArrayCollection([new UserNotificationSettings($this)]);
        $this->badges = new ArrayCollection();
    }

    public function getUserId(): int
    {
        return $this->getId();
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): void
    {
        // @phpstan-ignore-next-line
        $this->username = $username;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): void
    {
        $this->email = $email;
    }

    /**
     * @return non-empty-string
     */
    public function getUserIdentifier(): string
    {
        return $this->username ?: 'unknown';
    }

    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }

    /**
     * @return Collection<int, Role>
     */
    public function getRoleEntities(): Collection
    {
        return $this->roles;
    }

    /**
     * @param Collection<int, Role>|array<Role> $roles
     */
    public function setRoleEntities(Collection|array $roles): void
    {
        $this->roles = $roles instanceof Collection
            ? $roles
            : new ArrayCollection($roles);
    }

    public function addRoleEntity(Role $role): void
    {
        $this->roles->add($role);
    }

    public function getPassword(): string
    {
        return $this->password ?? '';
    }

    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    public function getDisplayName(): string
    {
        return $this->displayName ?: $this->getUsername();
    }

    public function setDisplayName(string $displayName): void
    {
        $this->displayName = $displayName;
    }

    public function getLanguage(): string
    {
        return $this->language;
    }

    public function setLanguage(string $language): void
    {
        $this->language = $language;
    }

    public function getTimezone(): string
    {
        return $this->timezone ?? 'UTC';
    }

    public function setTimezone(?string $timezone): void
    {
        $this->timezone = $timezone;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): void
    {
        $this->avatar = $avatar;
    }

    public function getSignature(): ?string
    {
        return $this->signature;
    }

    public function setSignature(?string $signature): void
    {
        $this->signature = $signature;
    }

    #[Deprecated()]
    public function eraseCredentials(): void
    {
    }

    public function isEmailVerified(): bool
    {
        return $this->emailVerified;
    }

    public function setEmailVerified(bool $emailVerified): void
    {
        $this->emailVerified = $emailVerified;
    }

    public function isBanned(): bool
    {
        return $this->banned;
    }

    public function setBanned(bool $banned): void
    {
        $this->banned = $banned;
    }

    public function getLastActivity(): ?DateTime
    {
        return $this->lastActivity;
    }

    public function setLastActivity(DateTime $lastActivity): void
    {
        $this->lastActivity = $lastActivity;
    }

    public function isOnline(int $withinLastSeconds = 300): bool
    {
        $lastActivity = $this->getLastActivity();
        if ($lastActivity === null) {
            return false;
        }

        $diff = time() - $lastActivity->getTimestamp();
        return $diff < $withinLastSeconds;
    }

    /**
     * @return Collection<int, Subscription>
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function getNotificationSettings(): UserNotificationSettings
    {
        if ($this->notificationSettings->isEmpty()) {
            $this->notificationSettings = new ArrayCollection([new UserNotificationSettings($this)]);
        }
        /** @var UserNotificationSettings $settings */
        $settings = $this->notificationSettings->first();
        return $settings;
    }

    public function setNotificationSettings(UserNotificationSettings $notificationSettings): void
    {
        $this->notificationSettings = new ArrayCollection([$notificationSettings]);
    }

    /**
     * @return Collection<int, Badge>
     */
    public function getBadges(): Collection
    {
        return $this->badges;
    }

    /**
     * @param array<Badge>|Collection<int, Badge> $badges
     */
    public function setBadges(array|Collection $badges): void
    {
        $this->badges = $badges instanceof Collection
            ? $badges
            : new ArrayCollection($badges);
    }

    public function getOAuthClient(): ?OAuthClient
    {
        return $this->oAuthClient;
    }

    public function setOAuthClient(?OAuthClient $oAuthClient): void
    {
        $this->oAuthClient = $oAuthClient;
    }

    public function getIdentifierForAudit(): string
    {
        return (string)$this->getId();
    }

    public function getNameForAudit(): string
    {
        return $this->getUserIdentifier();
    }
}

src/Cms/Controller/Frontend/PageController.php
<?php

declare(strict_types=1);

namespace Forumify\Cms\Controller\Frontend;

use DateTime;
use Forumify\Cms\Entity\Page;
use Forumify\Core\Controller\IndexController;
use Forumify\Cms\Repository\PageRepository;
use Forumify\Core\Security\VoterAttribute;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Twig\Environment;

class PageController extends AbstractController
{
    public function __construct(
        private readonly Environment $twig,
        private readonly PageRepository $pageRepository,
    ) {
    }

    #[Route('/{urlKey?}', 'page', requirements: ['urlKey' => '.*'], priority: -250)]
    public function __invoke(string $urlKey = ''): Response
    {
        $page = $this->pageRepository->findOneByUrlKey($urlKey);
        if ($page === null) {
            if (empty($urlKey)) {
                return $this->forward(IndexController::class);
            }
            throw $this->createNotFoundException("Page with url '$urlKey' not found.");
        }

        $this->denyAccessUnlessGranted(VoterAttribute::ACL->value, [
            'entity' => $page,
            'permission' => 'view',
        ]);

        if ($page->getType() === Page::TYPE_TWIG) {
            return $this->render($page->getUrlKey(), [
                'page' => $page,
            ]);
        }

        return $this->render('@Forumify/frontend/cms/page.html.twig', [
            'page' => $page,
            'tree' => json_decode($page->getTwig(), true, 512, JSON_THROW_ON_ERROR),
        ]);
    }

    #[Route('/page/{slug:page}/css', 'page_css')]
    public function css(Page $page, Request $request): Response
    {
        $lastModified = $page->getUpdatedAt() ?? $page->getCreatedAt();
        return $this->ifModifiedSince($request, $lastModified, $page->getCss(...), [
            'Content-Type' => 'text/css',
        ]);
    }

    #[Route('/page/{slug:page}/javascript', 'page_js')]
    public function javascript(Page $page, Request $request): Response
    {
        $lastModified = $page->getUpdatedAt() ?? $page->getCreatedAt();
        return $this->ifModifiedSince($request, $lastModified, $page->getJavascript(...), [
            'Content-Type' => 'text/javascript',
        ]);
    }

    /**
     * @param Request $request
     * @param DateTime $lastModified
     * @param callable(): (string|null) $getContent
     * @param array<string, string> $headers
     * @return Response
     */
    private function ifModifiedSince(Request $request, DateTime $lastModified, callable $getContent, array $headers = []): Response
    {
        $response = new Response();
        $response->setLastModified($lastModified);
        $response->setPublic();
        if ($response->isNotModified($request)) {
            return $response;
        }

        $content = $getContent();
        if (!empty($content)) {
            $content = $this->twig->createTemplate($content)->render();
        }

        $response->setContent($content);
        $response->headers->add($headers);
        return $response;
    }
}

templates/frontend/components/comment_list.html.twig
{% embed '@Forumify/components/list.html.twig' with { class: '' } %}
    {% block list %}
        <ul class="flex flex-col gap-4">
            {% for item in this.result.rows %}
                {% block row %}
                    {% include '@Forumify/frontend/components/comment_list_comment.html.twig' %}
                {% endblock %}
            {% else %}
                {% block empty %}
                {% endblock %}
            {% endfor %}
        </ul>
    {% endblock %}
    {% block pagination_top %}
        {% include '@Forumify/components/components/pagination.html.twig' with { class: 'box p-2 mb-4' } %}
    {% endblock %}
    {% block pagination_bottom %}
        {% include '@Forumify/components/components/pagination.html.twig' with { class: 'box p-2 mt-4' } %}
    {% endblock %}
{% endembed %}

templates/frontend/components/comment_list_comment.html.twig
{% block comment_list_comment %}
    {% set isAnswer = topic.answer is not null and topic.answer.id == item.id %}
    <li class="comment box{% if isAnswer %} answer{% endif %}" {{ stimulus_controller('forumify/comment-editor', {
        updateUrl: path('forumify_forum_comment_edit', { id: item.id })
    }) }}>
        {% block comment_list_comment_author %}
            <div class="comment-author">
                {% include '@Forumify/components/avatar.html.twig' with { user: item.createdBy } only %}
                {% include '@Forumify/components/username.html.twig' with { user: item.createdBy, className: 'text-center' } only %}
                {% if item.createdBy %}
                    {% block comment_list_comment_author_username %}
                        {% if not setting('forumify.hide_usernames') %}
                            <span class="text-small">@{{ item.createdBy.username }}</span>
                        {% endif %}
                    {% endblock %}
                    {% block comment_list_comment_author_roles %}
                        {% set roles = item.createdBy.roleEntities|filter(r => r.showOnForum) %}
                        {% if roles is not empty %}
                            <ul class="flex flex-col mt-4 text-small text-center hide-phone">
                                {% for role in roles %}
                                    <li {% if role.color is not null and role.color != '#000000' %}style="color: {{ role.color }};"{% endif %}>
                                        {{ role.title }}
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endblock %}
                    {% block comment_list_comment_author_badges %}
                        <div class="flex flex-wrap justify-center gap-2 mt-4 hide-phone">
                            {% for badge in item.createdBy.badges|filter(b => b.showOnForum) %}
                                <div class="avatar-sm flex justify-center items-center">
                                    <img width="100%" height="auto" src="{{ asset(badge.image, 'forumify.asset') }}" title="{{ badge.name }}">
                                </div>
                            {% endfor %}
                        </div>
                    {% endblock %}
                {% endif %}
            </div>
        {% endblock %}
        {% block comment_list_comment_comment %}
            <div class="comment-content">
                <div class="pl-4 pr-4 flex-grow">
                    <div class="text-small text-secondary flex justify-between items-end">
                        {% block comment_list_comment_content_created_at %}
                            <span class="mb-2 flex flex-col">
                                {{ item.createdAt|format_date }}
                                {% if item.updatedAt != item.createdAt and item.updatedBy is not null %}
                                    {% set editor = item.updatedBy %}
                                    <span class="text-light text-extra-small hide-phone">
                                        {{ 'comment.edited'|trans({
                                            user: editor.displayName|default(editor.username),
                                            date: item.updatedAt|format_date
                                        }) }}
                                    </span>
                                {% endif %}
                            </span>
                        {% endblock %}
                        {% block comment_list_comment_content_toolbar %}
                            <div class="comment-toolbar">
                                {% block comment_list_comment_content_toolbar_buttons %}
                                    {% if is_granted(constant('Forumify\\Core\\Security\\VoterAttribute::CommentEdit').value, item) %}
                                        <a
                                            class="btn-link btn-small btn-icon text-secondary"
                                            aria-label="{{ 'forum.comment.edit'|trans }}"
                                            {{ stimulus_action('forumify/comment-editor', 'toggleEdit') }}
                                        >
                                            <i class="ph ph-pencil"></i>
                                        </a>
                                    {% endif %}
                                    {% if is_granted(constant('Forumify\\Core\\Security\\VoterAttribute::CommentDelete').value, item) %}
                                        <a
                                            class="btn-link btn-small btn-icon text-secondary"
                                            aria-label="{{ 'forum.comment.delete'|trans }}"
                                            href="{{ path('forumify_forum_comment_delete', { id: item.id }) }}"
                                        >
                                            <i class="ph ph-trash"></i>
                                        </a>
                                    {% endif %}
                                {% endblock %}
                            </div>
                        {% endblock %}
                    </div>
                    {% block comment_list_comment_content %}
                        {{ item.content|rich }}
                    {% endblock %}
                    {% block comment_list_comment_comment_edit %}
                        {% if is_granted(constant('Forumify\\Core\\Security\\VoterAttribute::CommentEdit').value, item) %}
                            <div class="d-none rich-editor" {{ stimulus_target('forumify/comment-editor', 'editorContainer') }}>
                                <div class="flex justify-center items-center gap-2 mt-2">
                                    <button type="button" class="btn-outlined" {{ stimulus_action('forumify/comment-editor', 'discardEdit') }}>
                                        {{ 'cancel'|trans }}
                                    </button>
                                    <button type="button" class="btn-primary" {{ stimulus_action('forumify/comment-editor', 'save') }}>
                                        {{ 'save'|trans }}
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                    {% endblock %}
                </div>
                {% block comment_list_comment_signature %}
                    <div class="hide-phone">
                        {% if item.createdBy.signature|default('')|striptags(['img']) %}
                            <hr class="mb-4">
                            <div class="ml-4 mr-4">
                                {{ item.createdBy.signature|rich }}
                            </div>
                        {% endif %}
                    </div>
                {% endblock %}
                {% set showAnswerButton = item|can_mark_as_answer %}
                <hr class="mt-4">
                {% block comment_list_comment_actions %}
                    <div class="flex gap-2 p-2 items-end{% if showAnswerButton or isAnswer %} justify-between{% else %} justify-end{% endif %}">
                        {% block comment_list_comment_actions_answer %}
                            {% if showAnswerButton %}
                                <a href="{{ path('forumify_forum_comment_answer', { id: item.id }) }}" class="btn-primary">
                                    <i class="ph ph-check-circle"></i>
                                    {{ 'forum.comment.mark_answer'|trans }}
                                </a>
                            {% elseif isAnswer %}
                                <div class="alert-success p-2 text-small">
                                    <i class="ph ph-check-circle"></i>
                                    {{ 'forum.comment.is_answer'|trans }}
                                </div>
                            {% endif %}
                        {% endblock %}
                        {% block comment_list_comment_actions_reactions %}
                            {{ component('CommentReactions', { comment: item }) }}
                        {% endblock %}
                    </div>
                {% endblock %}
            </div>
        {% endblock %}
    </li>
{% endblock %}

templates/frontend/components/comment_reactions.html.twig
<div class="flex gap-1 justify-end" {{ attributes }} data-poll="delay(30000)|$render">
    {% for reaction in this.groupedReactions %}
        <a
            class="btn-small {{ this.userReacted(reaction.id) ? 'btn-outlined-highlighted' : 'btn-outlined' }}"
            data-action="live#action"
            data-live-action-param="toggleReaction"
            data-live-reaction-id-param="{{ reaction.id }}"
        >
            <img class="reaction mr-1" src="{{ asset(reaction.image, 'forumify.asset') }}" alt="">
            {{ reaction.count }}
        </a>
    {% endfor %}
    <div {{ stimulus_controller('forumify/menu', { placement: 'bottom-end' }) }}>
        <a
            class="btn-small btn-outlined btn-icon"
            aria-label="{{ 'forum.comment.reactions'|trans }}"
            {{ stimulus_target('forumify/menu', 'openButton') }}
        >
            <i class="ph ph-smiley"></i>
        </a>
        <div class="reactions-menu" {{ stimulus_target('forumify/menu', 'menu') }}>
            <input type="text" placeholder="{{ 'search'|trans }}" data-model="reactionSearch">
            <div class="flex flex-wrap gap-2 mt-2">
                {% for reaction in this.reactions %}
                    <button
                        class="btn-small btn-link"
                        data-action="live#action"
                        data-live-action-param="toggleReaction"
                        data-live-reaction-id-param="{{ reaction.id }}"
                        data-live-allow-remove="0"
                        aria-label="{{ reaction.name }}"
                    >
                        <img class="reaction" src="{{ asset(reaction.image, 'forumify.asset') }}" alt="{{ reaction.name }}">
                    </button>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/frontend/components/notifications.html.twig
<div {{ attributes }} data-poll="delay(30000)|$render">
    {% set unseenCount = this.unseenCount %}
    <div {{ stimulus_controller('forumify/menu', { hideAdornment: true, placement: 'bottom-end' }) }}>
        <a
            class="btn-link btn-icon"
            data-action="live#action"
            data-live-action-param="markAsRead"
            aria-label="{{ 'view_notifications'|trans }}"
            {{ stimulus_target('forumify/menu', 'openButton') }}
        >
            {% if unseenCount > 0 %}
                <i class="ph ph-bell-ringing"></i>{{ unseenCount }}
            {% else %}
                <i class="ph ph-bell"></i>
            {% endif %}
        </a>
        <ul class="menu" {{ stimulus_target('forumify/menu', 'menu') }}>
            {% set notifications = this.notifications %}
            {% for notification in notifications %}
                {% set notificationType = this.notificationType(notification) %}
                {% if notificationType is not null %}
                    <li class="p-3 flex gap-2 notification">
                        {% set image = notificationType.image(notification) %}
                        {% if image is not empty %}
                            <img width="48px" height="48px" style="object-fit: contain" src="{{ notificationType.image(notification) }}" alt="">
                        {% endif %}
                        <div>
                            {% set notificationTitle %}
                                <p class="text-subtitle {% if not notification.seen %}text-bold{% endif %}">
                                    {{ notificationType.title(notification) }}
                                </p>
                            {% endset %}
                            {% set notificationUrl = notificationType.url(notification) %}
                            {% if notificationUrl is not empty %}
                                <a href="{{ notificationUrl }}">{{ notificationTitle }}</a>
                            {% else %}
                                {{ notificationTitle }}
                            {% endif %}
                            <p class="text-small">
                                {{ notificationType.description(notification) }}
                            </p>
                        </div>
                    </li>
                {% endif %}
            {% else %}
                <div class="flex justify-center p-6">
                    {{ 'no_notifications'|trans }}
                </div>
            {% endfor %}
            {% if unseenCount > notifications|length %}
                <hr>
                <li class="p-3 flex justify-center">
                    <a href="">See all notifications</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
{% macro placeholder(props) %}
    <a class="btn-link btn-icon" href="">
        <i class="ph ph-bell"></i>
    </a>
{% endmacro %}

templates/frontend/components/profile_header.html.twig
<div class="grid-2">
    {% block profile_avatar %}
        <div class="text-right border-r pr-3 mr-3">
            {% include '@Forumify/components/avatar.html.twig' with {
                user: user,
                className: 'avatar-lg',
            } only %}
        </div>
    {% endblock %}
    {% block profile_user %}
        <div>
            <div class="flex gap-2 mb-2">
                {% block profile_user_username %}
                    <div>
                        <h2 class="mb-0">
                            {{ user.displayName }}
                            {% if user.oAuthClient %}
                                <span class="tag text-regular ml-2">APP</span>
                            {% endif %}
                        </h2>
                        {% if not setting('forumify.hide_usernames') %}
                            <p class="text-small">@{{ user.username }}</p>
                        {% endif %}
                    </div>
                {% endblock %}
                {% block profile_user_actions %}
                    {% if this.showUserActions and app.user is not null and app.user.id != user.id %}
                        <a
                            class="btn-outlined btn-icon"
                            aria-label="{{ 'profile.message'|trans }}"
                            href="{{ path('forumify_forum_messenger_thread_create', { recipient: user.id }) }}"
                        >
                            <i class="ph ph-paper-plane-tilt"></i>
                        </a>
                        {{ component('SubscribeButton', {
                            entityId: user.id,
                            subscriptionType: 'user_follow',
                            subscribeIcon: '',
                            subscribeLabel: 'follow',
                            unsubscribeIcon: '',
                            unsubscribeLabel: 'unfollow',
                            buttonClass: 'btn-outlined'
                        }) }}
                    {% endif %}
                {% endblock %}
            </div>
            {% block profile_user_roles %}
                {% set roles = user.roleEntities|filter(r => r.showOnForum) %}
                {% if roles is not empty %}
                    <ul class="flex flex-col mb-2 text-small">
                        {% for role in roles %}
                            <li {% if role.color is not null and role.color != '#000000' %}style="color: {{ role.color }};"{% endif %}>
                                {{ role.title }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endblock %}
            {% block profile_user_stats %}
                <p class="mb-2">
                    <span class="text-bold">{{ this.topicCount }}</span> {{ 'profile.topics'|trans }}
                    <span class="text-bold ml-4">{{ this.commentCount }}</span> {{ 'profile.comments'|trans }}
                </p>
                <p class="mb-4">
                    <span class="text-bold">{{ this.followerCount }}</span> {{ 'profile.followers'|trans }}
                    <span class="text-bold ml-4">{{ this.followingCount }}</span> {{ 'profile.following'|trans }}
                </p>
            {% endblock %}
            {% block profile_user_timestamps %}
                <p class="text-small">{{ 'profile.registered'|trans({ date: user.createdAt|date('d M Y') })  }}</p>
                <p class="text-small">{{ 'profile.last_seen'|trans({ date: user.lastActivity is not null ? user.lastActivity|format_date : 'never' })   }}</p>
            {% endblock %}
        </div>
    {% endblock %}
</div>

templates/frontend/components/subscribe_button.html.twig
<div {{ attributes }}>
    {% if app.user is null %}
        <a class="{{ this.buttonClass }}" href="{{ path('forumify_core_login', { '_target_path': app.request.requestUri }) }}">
            {% if this.subscribeIcon is not empty %}
                <i class="{{ this.subscribeIcon }}"></i>
            {% endif %}
            <span class="hide-phone ml-2">{{ this.subscribeLabel|trans }}
        </a>
    {% else %}
        {% set subscription = this.subscription %}
        <button class="{{ this.buttonClass }}" data-action="live#action" data-live-action-param="toggleSubscription">
            {% if subscription is null %}
                {% if this.subscribeIcon is not empty %}
                    <i class="{{ this.subscribeIcon }}"></i>
                {% endif %}
                <span class="hide-phone ml-2">{{ this.subscribeLabel|trans }}
            {% else %}
                {% if this.unsubscribeIcon is not empty %}
                    <i class="{{ this.unsubscribeIcon }}"></i>
                {% endif %}
                <span class="hide-phone ml-2">{{ this.unsubscribeLabel|trans }}
            {% endif %}
        </button>
    {% endif %}
</div>